### ISSUE TITLE
Want some problematic cases ?

### ISSUE THREAD

**Issue by Vilo176** [gcherchi/FastAndRobustMeshArrangements#13]
Hi,

I've just read the paper behind this code, and it is very interesting.
I think your approach could be a real breakthrough toward "real life" applications.

My point is to compute all split parts of a soup of triangles.
Next step is to make CSG with the result, but it is out of the scope of this post.
Geometry is coming from architectural software (Revit, ArchiCAD, IFC, ...).

Prior to your work, I interested myself to a couple of others approach in the CSG world, among others EPUG, LibIGL, Tetwild, CGAL, OpenCascade, ...
None of them have a "production grade" level of robustness and efficiency.
The problem is that, once you give them real world cases, the dream is broken, especially with geometry coming from construction world, with many almost aligned faces, slightly overlapping solids, fillets, etc ...

So, I don't know if your work is a pure proof of concept, or if you plane to make it a real world grade solution.
If you plan to develop the concept, then I can give you simple cases (~10k triangles) that give fatal issues in the current implementation available in this repo.

Let me know !

**Comment by Vilo176** [comment]
Seams that 99% of my issues was due to bad compilation ...

Questions still remain :
- Do you plan to maintain and develop this framework or is it just a poco ?
- Are there already any means to know for sure if the result is actually good or has mistakes ?
- Do you plan to replace the Earcut algo with Delaunay, so that cut triangles have better shapes ?
- Do you plan to enhance the label mechanism, that is currently limited to 32 labels max, to allow more (unlimited) ?

Thanks again for this awesome work !

**Comment by mlivesu** [comment]
Hi Vilo176, I'll try to address your points one by one

**Do you plan to maintain and develop this framework or is it just a poco ?**
Absolutely! We are actually working towards robust and efficient tools that internally rely on this building block. The first thing that is going to be released is unconditionally robust mesh booleans with topological propagation of the inside/outside labels. We're almost there, stay tuned

**Are there already any means to know for sure if the result is actually good or has mistakes ?**
Topologically, the output is always guaranteed to be correct. Geometrically, in the last step we perform heuristic snap rounding to assign xyz coordinates to implicit intersection points, therefore we may still introduce errors. This is very unlikely to happen, but if you want to be sure geometry is safe you can just re-run the program on the output geometry. If the result was correct no intersections or degenerate elements will be found (intersection checks on the input mesh are exact)

**Do you plan to replace the Earcut algo with Delaunay, so that cut triangles have better shapes ?**
This could be easily done, but it's not top priority in our todo list. A cheap alternative could be to use randomized or prioritized earcut. I've recently added these features to cinolib and this code is based on my library, so it should be a smooth transition

**Do you plan to enhance the label mechanism, that is currently limited to 32 labels max, to allow more (unlimited) ?**
Same as before. Keep in mind that everything has a cost. We expanded the number of labels for specific reasons (an application that demanded it). We would be happy to hear for applications where the need for such an extension compensates the overhead needed to support it

Finally, a question for you: after fixing you compilation issues, did you still have failure cases? If so, we would be happy to take a look at them!

**Comment by Vilo176** [comment]
Hi Marco,

Very nice to talk with you !
Thanks for your very clear explanations.

1. That's a very good news.
There is plenty of room for a proven robust & fast CSG tool, and I will follow your work very closely.

2. The tips consisting on recalling the algo on the split geometry is a good one, I'll check it.
Since the algo is very fast, this could be affordable.

3. This is a demand that is tightly bounded to my specific needs.
After split parts are computed, I want to perform a tetrahedralization on the result.
The better shaped the triangles are, the best chance I have to complete the 3D tetra step.
For example tools like TetGen or GMSH are very dependent to quality of input 2D triangulation.
But this can be quite easily addressed by giving well shaped triangles as input, and maybe make some adaptation to the output (MMG ...).

4. The label mechanism is important, once again, for my specific needs, because I have many simple object as input.
A typical case involves >1k solids, each having a different label.
Being able to reassign cut triangles to parents solids is mandatory to rebuild cut volumes, and finally having a full CSG.

Finally. I've indeed fixed some issue with compilation, and now algo is almost 100% stable.
I still have cases that lead to bad results.
What format do you prefer as input for these data ?

**Comment by Vilo176** [comment]
Here is a 1rst one
[Issue.zip](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/7739207/Issue.zip)

**Comment by mlivesu** [comment]
OBJ, STL, OFF or similar ASCII format are all fine with us

for (3): if your ultimate goal is to build volumetric meshes, I suggest you take a look at the recent work of Marco Attene and Lorenzo Diazzi ([link](https://github.com/MarcoAttene/VolumeMesher)). It is based on the same robust predicates we used for this tool. Making booleans with their volumetric tool is less efficient than making surface booleans, but if you will eventually tetrahedralize everything, making booleans directly on the volumes is more efficient

**Comment by Vilo176** [comment]
I've just made some early testing with "VolumeMesher", all I have to says until now is that my jaw is still on the floor ...

**Comment by mlivesu** [comment]
🤣 Marco and Lorenzo will be happy you liked it

**Comment by gcherchi** [comment]
Hi Vilo176,
I've tried your mesh, and the problem is in the final snap rounding step, as Marco suggested in a previous comment. I pre-processed your mesh with the heuristic we described in the last paragraph of section 5.6 of our paper (note that even this heuristic does not guarantee to solve the snap rounding problem, but it helps). I have attached the result to this message.
[output.zip](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/7756885/output.zip)
.

**Comment by Vilo176** [comment]
Hi Gianmarco,

Thanks a lot for your research.

> I pre-processed your mesh with the heuristic ...

If I understand well, I would have to :
1. Run algo on inital triangles soup with original coordinates
2. Convert resulting points coordinates to single precision (i.e. snap rounding)
3. ReRun the algo

?

**Comment by gcherchi** [comment]
Dear Vilo176,
the heuristic approach we described in the paper is the following:
1. pre-process the input mesh IM by casting the vertices coordinates to float and save it as IM'
2. call the mesh_arrangement passing the pre-processed mesh IM' as input
If you need more information, you can contact me by e-mail :)
