### ISSUE TITLE
Triangulation is an endless loop

### ISSUE THREAD

**Issue by GridGeneration** [gcherchi/FastAndRobustMeshArrangements#24]
[meshccc.stl.gz](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/15032673/meshccc.stl.gz)
[hello]() ,this mesh is an endless loop while call inline void solveIntersections(const std::vector<double> &in_coords, const std::vector<uint> &in_tris, const std::vector<uint> &in_labels, point_arena &arena,
                               std::vector<double> &out_coords, std::vector<uint> &out_tris, std::vector< std::bitset<NBIT> > &out_labels);

**Comment by gcherchi** [comment]
Hi,
I tried your model and had no problems. Here I attach the generated [result](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/15042037/output.obj.zip).
Yesterday we uploaded a new version of the code, probably the problem was related to the previous version.
NB: in the final result there are still 2 intersections, but they are due to a snap rounding problem.
